image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npm install
      gp sync-done install
    command: npm run dev
  - init: gp sync-await install
    command: npm run e2e 

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 10000
    onOpen: ignore 

vscode:
  extensions:
    - 9j.amvim
    - vscode.github
    - vscodevim.vim
